#!/usr/bin/env node
/**
 * Interactive setup script for the vision service.
 *
 * What it does:
 *   1. Prompts for ANTHROPIC_API_KEY (required) and OPENAI_API_KEY (optional)
 *   2. Prompts for VISION_SERVICE_URL (defaults to http://localhost:8765)
 *   3. Tests each key by making a real (but minimal) API call
 *   4. Writes a .env file to services/vision-service/.env
 *   5. Prints next steps
 *
 * Why a .mjs script rather than a compiled TS binary?
 *   Zero build step — runs directly with `node scripts/setup.mjs`.
 *   No dependency on the SDK's own build output, so it works on a fresh clone
 *   before `pnpm install` has even been run (uses only Node built-ins).
 *
 * Run:
 *   node scripts/setup.mjs
 *   OR (after root pnpm install):
 *   pnpm setup
 */

import readline from "readline/promises";
import { stdin as input, stdout as output } from "process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, "services", "vision-service", ".env");

// ANSI colour helpers — degrade gracefully if terminal doesn't support them
const c = {
  reset:  "\x1b[0m",
  bold:   "\x1b[1m",
  dim:    "\x1b[2m",
  green:  "\x1b[32m",
  yellow: "\x1b[33m",
  red:    "\x1b[31m",
  cyan:   "\x1b[36m",
};

function print(msg) { process.stdout.write(msg + "\n"); }
function success(msg) { print(`${c.green}✓${c.reset}  ${msg}`); }
function warn(msg)    { print(`${c.yellow}⚠${c.reset}  ${msg}`); }
function error(msg)   { print(`${c.red}✗${c.reset}  ${msg}`); }
function info(msg)    { print(`${c.dim}   ${msg}${c.reset}`); }
function header(msg)  { print(`\n${c.bold}${c.cyan}${msg}${c.reset}`); }

// ---------------------------------------------------------------------------
// API key validation
// ---------------------------------------------------------------------------
// We make the cheapest possible real API call to verify the key works:
//   Anthropic: list models endpoint (GET, no tokens consumed)
//   OpenAI:    list models endpoint (GET, no tokens consumed)
//
// This surfaces auth errors (wrong key, revoked key) immediately rather than
// at the first Vision strategy invocation during a test run.
// ---------------------------------------------------------------------------

async function testAnthropicKey(apiKey) {
  try {
    const res = await fetch("https://api.anthropic.com/v1/models", {
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
    });
    return res.ok;
  } catch {
    return false;
  }
}

async function testOpenAIKey(apiKey) {
  try {
    const res = await fetch("https://api.openai.com/v1/models", {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    return res.ok;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// .env writer
// ---------------------------------------------------------------------------
function writeEnv({ anthropicKey, openaiKey, visionServiceUrl }) {
  const lines = [
    "# Generated by: node scripts/setup.mjs",
    `# Created: ${new Date().toISOString()}`,
    "",
    "# Primary vision provider (Claude)",
    anthropicKey
      ? `ANTHROPIC_API_KEY=${anthropicKey}`
      : "# ANTHROPIC_API_KEY=  ← not configured",
    "",
    "# Fallback vision provider (GPT-4V) — optional",
    openaiKey
      ? `OPENAI_API_KEY=${openaiKey}`
      : "# OPENAI_API_KEY=  ← not configured",
    "",
    "# URL of this running service (used by the TypeScript SDK)",
    `VISION_SERVICE_URL=${visionServiceUrl}`,
    "",
  ];

  fs.writeFileSync(ENV_PATH, lines.join("\n"), "utf8");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  header("Browser Agent Element Selector — Vision Service Setup");
  print(`${c.dim}This configures the Python vision service that powers the Vision fallback strategy.${c.reset}`);
  print(`${c.dim}Your API keys are stored locally in: services/vision-service/.env${c.reset}\n`);

  const rl = readline.createInterface({ input, output });

  // ── Anthropic API key ────────────────────────────────────────────────────
  print(`${c.bold}1. Anthropic API Key${c.reset} ${c.dim}(required for Claude vision — primary provider)${c.reset}`);
  info("Get yours at: https://console.anthropic.com/settings/keys");

  let anthropicKey = "";
  let anthropicValid = false;

  while (true) {
    anthropicKey = (await rl.question("   Enter ANTHROPIC_API_KEY: ")).trim();

    if (!anthropicKey) {
      warn("Anthropic key is required for the Vision strategy to work.");
      const skip = await rl.question("   Skip and configure later? (y/N): ");
      if (skip.toLowerCase() === "y") {
        warn("Skipping Anthropic key — Vision strategy will return 503 until configured.");
        break;
      }
      continue;
    }

    process.stdout.write("   Testing key... ");
    anthropicValid = await testAnthropicKey(anthropicKey);

    if (anthropicValid) {
      success("Anthropic key is valid.");
      break;
    } else {
      error("Key rejected by Anthropic API. Check for typos or try a new key.");
      const retry = await rl.question("   Try again? (Y/n): ");
      if (retry.toLowerCase() === "n") break;
    }
  }

  // ── OpenAI API key ───────────────────────────────────────────────────────
  print(`\n${c.bold}2. OpenAI API Key${c.reset} ${c.dim}(optional — GPT-4V fallback if Claude is unavailable)${c.reset}`);
  info("Get yours at: https://platform.openai.com/api-keys");

  let openaiKey = "";

  const wantOpenAI = await rl.question("   Configure OpenAI fallback? (y/N): ");
  if (wantOpenAI.toLowerCase() === "y") {
    while (true) {
      openaiKey = (await rl.question("   Enter OPENAI_API_KEY: ")).trim();
      if (!openaiKey) break;

      process.stdout.write("   Testing key... ");
      const openaiValid = await testOpenAIKey(openaiKey);

      if (openaiValid) {
        success("OpenAI key is valid.");
        break;
      } else {
        error("Key rejected by OpenAI API.");
        const retry = await rl.question("   Try again? (Y/n): ");
        if (retry.toLowerCase() === "n") break;
      }
    }
  } else {
    info("Skipped — Claude will be used exclusively.");
  }

  // ── Vision service URL ───────────────────────────────────────────────────
  print(`\n${c.bold}3. Vision Service URL${c.reset} ${c.dim}(where the Python service will run)${c.reset}`);
  info("Default is http://localhost:8765 — change this for Docker/remote deployments.");

  const urlInput = await rl.question("   VISION_SERVICE_URL [http://localhost:8765]: ");
  const visionServiceUrl = urlInput.trim() || "http://localhost:8765";
  success(`Service URL set to: ${visionServiceUrl}`);

  rl.close();

  // ── Write .env ───────────────────────────────────────────────────────────
  print(`\n${c.bold}Writing configuration...${c.reset}`);

  // Ensure the directory exists (in case vision-service hasn't been set up yet)
  fs.mkdirSync(path.dirname(ENV_PATH), { recursive: true });

  writeEnv({ anthropicKey, openaiKey, visionServiceUrl });
  success(`Saved to: ${ENV_PATH}`);

  // ── Summary ──────────────────────────────────────────────────────────────
  header("Setup complete. Next steps:");

  print(`${c.bold}1. Start the vision service:${c.reset}`);
  print(`   cd services/vision-service`);
  print(`   uv run uvicorn vision_service.main:app --port 8765\n`);

  print(`${c.bold}2. Install SDK dependencies:${c.reset}`);
  print(`   pnpm install\n`);

  print(`${c.bold}3. Run unit tests (no service needed):${c.reset}`);
  print(`   cd packages/locator-sdk && pnpm test\n`);

  print(`${c.bold}4. Run E2E tests (service must be running):${c.reset}`);
  print(`   cd packages/locator-sdk && pnpm test:e2e\n`);

  if (!anthropicValid) {
    warn("Anthropic key was not validated. Vision strategy will not work until a valid key is added.");
    info(`Edit ${ENV_PATH} and re-run this script to validate.`);
  }
}

main().catch((err) => {
  error(`Setup failed: ${err.message}`);
  process.exit(1);
});
